apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: custom
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
